# Copyright 2020 Canonical
# See LICENSE file for licensing details.

options:
  influxdb-hostname:
    default: ""
    description: The hostname of the remote influxdb to submit metrics to
    type: string
  influxdb-port:
    default: 8086
    description: The port of the remote influxdb to submit metrics to
    type: int
  influxdb-username:
    default: ""
    description: The influxdb username
    type: string
  influxdb-password:
    default: ""
    description: The influxdb password
    type: string
  influxdb-database:
    default: ""
    description: The influxdb database to use
    type: string
  dry-run:
    default: false
    type: boolean
    description: Whether to run in dry-run mode and not submit to the influxdb
  http-proxy:
    default: ""
    description: What to write to http_proxy in /etc/environment
    type: string
  https-proxy:
    default: ""
    description: What to write to https_proxy in /etc/environment
    type: string
  no-proxy:
    default: ""
    description: What to write to no_proxy in /etc/environment
    type: string
