---
name: CI

on: [push, pull_request]

jobs:
  run-tests:
    uses: ./.github/workflows/pytest.yml
  linter:
    uses: ./.github/workflows/linter.yml
  tflint:
    uses: ./.github/workflows/tflint.yml
