---
name: Lint Code Base

on:
  workflow_call:

jobs:
  build:
    name: Run terraform linter
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Terraform linter
        run: |
          #/bin/bash
          set -ex
          sudo snap install tflint
          tflint --recursive
